export const DEFAULT_CATEGORIES: { name: string; group: string }[] = [
  { name: 'Rent', group: 'ESSENTIAL' },
  { name: 'Food', group: 'ESSENTIAL' },
  { name: 'Electricity', group: 'ESSENTIAL' },
  { name: 'Water', group: 'ESSENTIAL' },
  { name: 'Internet', group: 'ESSENTIAL' },
  { name: 'Transportation', group: 'ESSENTIAL' },
  { name: 'Healthcare', group: 'ESSENTIAL' },
  { name: 'Insurance', group: 'ESSENTIAL' },
  { name: 'Education', group: 'ESSENTIAL' },
  { name: 'Clothing', group: 'PERSONAL' },
  { name: 'Entertainment', group: 'PERSONAL' },
  { name: 'Eating Out', group: 'PERSONAL' },
  { name: 'Shopping', group: 'PERSONAL' },
  { name: 'Subscriptions', group: 'PERSONAL' },
  { name: 'Family Support', group: 'FAMILY_SOCIAL' },
  { name: 'Gifts', group: 'FAMILY_SOCIAL' },
  { name: 'Weddings', group: 'FAMILY_SOCIAL' },
  { name: 'Emergencies', group: 'FAMILY_SOCIAL' },
  { name: 'Debt Payments', group: 'FINANCIAL' },
  { name: 'Savings', group: 'FINANCIAL' },
  { name: 'Investments', group: 'FINANCIAL' },
  { name: 'Bank Fees', group: 'FINANCIAL' },
  { name: 'Business Capital', group: 'BUSINESS' },
  { name: 'Equipment', group: 'BUSINESS' },
  { name: 'Operations', group: 'BUSINESS' },
  { name: 'Salary', group: 'INCOME' },
  { name: 'Freelance', group: 'INCOME' },
  { name: 'Business Income', group: 'INCOME' },
  { name: 'Other Income', group: 'INCOME' },
];
